### ISSUE TITLE
Is a recording of the R Core panel discussion publicly available?

### ISSUE THREAD

**Issue by egnha** [eddelbuettel/user2022-r-core-panel#6]
Apologies for posing this question as an issue, but I couldn't find any such link on the [conference webpage](https://user2022.r-project.org), and thought that you (@eddelbuettel) might have a pointer. Thanks!

**Comment by eddelbuettel** [comment]
The conference organizer said all along that all material would remain on the conference platform for 30 days and accessible to conference attendees, and be on YouTube! (as I recall) thereafter.  So in a matter of days there should be a public link to this panel, and of course to the other content.
